[tool.poetry]
package-mode = false

[project]
name = "kline-data-collector"
version = "0.1.0"
description = "High-throughput 1-minute klines and funding rate historical collector and normalization engine for crypto derivatives"
authors = [
    {name = "grishaSuperBoy", email = "333852748+grishaSuperBoy@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "requests (>=2.31.0,<3.0.0)",
    "pandas (>=2.2.0,<4.0.0)",
    "pyarrow (>=15.0.0,<27.0.0)",
    "numpy (>=1.26.0,<3.0.0)",
    "urllib3 (>=1.26.0,<3.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
